import type { Category } from './types';

export const CATEGORIES = [
  {
    id: 'sudaderas-chaquetas-pantalones',
    name: 'Sudaderas - Chaquetas - Pantalones',
    color: '#1B3A5C',
    foregroundColor: '#FFFFFF',
    fabricIds: [
      'vendaval-crushed-r',
      'orion-clororresistente',
      'gorek',
      'glou-crushed',
      't180',
      'universal-clororresistente',
      'microtec-clororresistente',
      'microprince',
      'fastrack',
    ],
  },
  {
    id: 'camisetas-polos',
    name: 'Camisetas - Polos',
    color: '#3FA9D5',
    foregroundColor: '#FFFFFF',
    fabricIds: [
      'apolo',
      'polux',
      'zanetti',
      'tikal-r',
      'cole-plus',
    ],
  },
  {
    id: 'uniforme-deportivo',
    name: 'Uniforme Deportivo',
    color: '#6CB33F',
    foregroundColor: '#FFFFFF',
    description: 'Camisetas y Pantalonetas',
    fabricIds: [
      'montesimone-r-antibacterial',
      'montesimone',
      'hydrotech',
      'hydrotech-antibacterial',
    ],
  },
  {
    id: 'uniforme-diario-faldas-blazers',
    name: 'Uniforme Diario - Faldas - Blazers',
    color: '#E91E8C',
    foregroundColor: '#FFFFFF',
    description: 'Faldas, Blazers, Pantalones',
    fabricIds: [
      'stefano-r',
      'dynamic',
      'microdrill',
      'alviero-stretch',
      'novastretch-lc',
      'universal-ripstop',
    ],
  },
  {
    id: 'buzos-hoodies-perchados',
    name: 'Buzos - Hoodies - Perchados',
    color: '#F7C948',
    foregroundColor: '#1a1a1a',
    fabricIds: [
      'fastrack',
      'celta',
      'dual',
      'microtitan-plus',
    ],
  },
  {
    id: 'chaquetas-prom',
    name: 'Chaquetas Prom',
    color: '#C42034',
    foregroundColor: '#FFFFFF',
    fabricIds: [
      'orion-clororresistente',
      'universal-clororresistente',
      'microtec-clororresistente',
      'alviero-stretch',
      'celta',
    ],
  },
  {
    id: 'blusas-camisas',
    name: 'Blusas - Camisas',
    color: '#7B4B94',
    foregroundColor: '#FFFFFF',
    fabricIds: [
      'metro-lc',
      'queen',
      'andes-r',
      'alessio',
    ],
  },
  {
    id: 'delantales-batas-laboratorio',
    name: 'Delantales - Batas de Laboratorio',
    color: '#F7941D',
    foregroundColor: '#1a1a1a',
    fabricIds: [
      'orion-clororresistente',
      'gorek',
      't180',
      'universal-clororresistente',
      'microdrill',
      'alviero-stretch',
    ],
  },
] as const satisfies readonly Category[];
