import type { Category } from './types';

// NOTE: color/foregroundColor are retained as structured data for programmatic use (e.g., inline styles in Phase 6).
// Source of truth for Tailwind styling: globals.css @theme tokens (bg-cat-*, text-cat-*-fg via CATEGORY_STYLE_MAP).
export const CATEGORIES = [
  {
    id: 'sudaderas-chaquetas-pantalones',
    name: 'Sudaderas - Chaquetas - Pantalones',
    color: '#1B3A5C',
    foregroundColor: '#FFFFFF',
    image: '/images/products/page04-0.webp',
    fabricIds: [
      'vendaval-crushed-r',
      'orion-clororresistente',
      'gorek',
      'glou-crushed',
      't180',
      'universal-clororresistente',
      'microtec-clororresistente',
      'microprince',
      'fastrack',
    ],
  },
  {
    id: 'camisetas-polos',
    name: 'Camisetas - Polos',
    color: '#3FA9D5',
    foregroundColor: '#FFFFFF',
    image: '/images/products/page06-8.webp',
    fabricIds: [
      'apolo',
      'polux',
      'zanetti',
      'tikal-r',
      'cole-plus',
    ],
  },
  {
    id: 'uniforme-deportivo',
    name: 'Uniforme Deportivo',
    color: '#6CB33F',
    foregroundColor: '#FFFFFF',
    description: 'Camisetas y Pantalonetas',
    image: '/images/products/page07-11.webp',
    fabricIds: [
      'montesimone-r-antibacterial',
      'montesimone',
      'hydrotech',
      'hydrotech-antibacterial',
    ],
  },
  {
    id: 'uniforme-diario-faldas-blazers',
    name: 'Uniforme Diario - Faldas - Blazers',
    color: '#E91E8C',
    foregroundColor: '#FFFFFF',
    description: 'Faldas, Blazers, Pantalones',
    image: '/images/products/page08-14.webp',
    fabricIds: [
      'stefano-r',
      'dynamic',
      'microdrill',
      'alviero-stretch',
      'novastretch-lc',
      'universal-ripstop',
    ],
  },
  {
    id: 'buzos-hoodies-perchados',
    name: 'Buzos - Hoodies - Perchados',
    color: '#F7C948',
    foregroundColor: '#1a1a1a',
    image: '/images/products/page09-20.webp',
    fabricIds: [
      'fastrack',
      'celta',
      'dual',
      'microtitan-plus',
    ],
  },
  {
    id: 'chaquetas-prom',
    name: 'Chaquetas Prom',
    color: '#C42034',
    foregroundColor: '#FFFFFF',
    image: '/images/products/page10-24.webp',
    fabricIds: [
      'orion-clororresistente',
      'universal-clororresistente',
      'microtec-clororresistente',
      'alviero-stretch',
      'celta',
    ],
  },
  {
    id: 'blusas-camisas',
    name: 'Blusas - Camisas',
    color: '#7B4B94',
    foregroundColor: '#FFFFFF',
    image: '/images/products/page11-29.webp',
    fabricIds: [
      'metro-lc',
      'queen',
      'andes-r',
      'alessio',
    ],
  },
  {
    id: 'delantales-batas-laboratorio',
    name: 'Delantales - Batas de Laboratorio',
    color: '#F7941D',
    foregroundColor: '#1a1a1a',
    image: '/images/products/page12-32.webp',
    imagePosition: 'center 20%',
    fabricIds: [
      'orion-clororresistente',
      'gorek',
      't180',
      'universal-clororresistente',
      'microdrill',
      'alviero-stretch',
    ],
  },
] as const satisfies readonly Category[];
