import type { Fabric } from './types';

export const FABRICS = [
  // === Sudaderas - Chaquetas - Pantalones ===
  {
    id: 'vendaval-crushed-r',
    name: 'Vendaval Crushed R',
    base: '23243',
    composition: '100% poliéster reciclado',
    weave: 'Plano',
    weight: '110 +-10 g/m2',
    width: '151 +- 2 cm',
    technologies: ['impermeabilidad', 'sostenible', 'antifluido-repelencia', 'proteccion-solar', 'clororresistente'],
    printRoutes: ['Unicolor', 'Davos'],
    image: '/images/products/page04-0.webp',
  },
  {
    id: 'orion-clororresistente',
    name: 'Orion Clororresistente',
    base: '22564',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '112 +-6 g/m2',
    width: '151 +- 3 cm',
    technologies: ['impermeabilidad', 'durabilidad', 'antifluido-repelencia', 'solidez-a-la-luz', 'proteccion-solar', 'clororresistente'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos'],
    image: '/images/products/page04-0.webp',
  },
  {
    id: 'gorek',
    name: 'Gorek',
    base: '23093',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '138 +-8 g/m2',
    width: '150 +- 2 cm',
    technologies: ['impermeabilidad', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos'],
    image: '/images/products/page04-0.webp',
  },
  {
    id: 'glou-crushed',
    name: 'Glou Crushed',
    base: '23091',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '135 +-5 g/m2',
    width: '152 +- 2 cm',
    technologies: ['impermeabilidad', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Davos'],
    image: '/images/products/page04-0.webp',
  },
  {
    id: 't180',
    name: 'T180',
    base: '22329',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '133 +-7 g/m2',
    width: '183 +- 3 cm',
    technologies: ['durabilidad', 'antifluido-repelencia', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page04-0.webp',
  },
  {
    id: 'universal-clororresistente',
    name: 'Universal Clororresistente',
    base: '22967',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '133 +-7 g/m2',
    width: '150 +- 3 cm',
    technologies: ['durabilidad', 'antifluido-repelencia', 'proteccion-solar', 'clororresistente'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos'],
    image: '/images/products/page04-0.webp',
  },
  {
    id: 'microtec-clororresistente',
    name: 'Microtec Clororresistente',
    base: '22280',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '104 +-6 g/m2',
    width: '152 +- 2 cm',
    technologies: ['durabilidad', 'antifluido-repelencia', 'proteccion-solar', 'clororresistente'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos'],
    image: '/images/products/page04-0.webp',
  },
  {
    id: 'microprince',
    name: 'Microprince',
    base: '22149',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '147 +-8 g/m2',
    width: '151 +- 2 cm',
    technologies: ['antifluido-repelencia', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page04-0.webp',
  },
  {
    id: 'fastrack',
    name: 'Fastrack',
    base: '33510',
    composition: '100% poliéster',
    weave: 'Punto',
    weight: '197 +-10 g/m2',
    width: '163 +- 4 cm',
    technologies: ['proteccion-solar', 'termico'],
    printRoutes: ['Unicolor', 'Davos', 'Sublimación'],
    image: '/images/products/page04-0.webp',
  },
  // === Camisetas - Polos ===
  {
    id: 'apolo',
    name: 'Apolo',
    base: '33622',
    composition: '60% poliéster, 40% algodón',
    weave: 'Punto',
    weight: '178 +-5 g/m2',
    width: '176 +- 3 cm',
    technologies: ['control-humedad', 'libertad-de-movimiento', 'algodon'],
    printRoutes: ['Unicolor'],
    image: '/images/products/page06-8.webp',
    isNew: true,
  },
  {
    id: 'polux',
    name: 'Polux',
    base: '33470',
    composition: '100% poliéster',
    weave: 'Punto',
    weight: '223 +-13 g/m2',
    width: '183 +- 4 cm',
    technologies: ['control-humedad', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page06-8.webp',
  },
  {
    id: 'zanetti',
    name: 'Zanetti',
    base: '33413',
    composition: '100% poliéster',
    weave: 'Punto',
    weight: '146 +-7 g/m2',
    width: '173 +- 3 cm',
    technologies: ['control-humedad', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos'],
    image: '/images/products/page06-8.webp',
  },
  {
    id: 'tikal-r',
    name: 'Tikal R',
    base: '33583',
    composition: '100% poliéster reciclado',
    weave: 'Punto',
    weight: '208 +-8 g/m2',
    width: '183 +- 4 cm',
    technologies: ['control-humedad', 'sostenible', 'antibacterial', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page06-8.webp',
  },
  {
    id: 'cole-plus',
    name: 'Cole Plus',
    base: '44672',
    composition: '100% poliéster',
    weave: 'Punto',
    weight: '161 +-8 g/m2',
    width: '200 +- 3 cm',
    technologies: ['desempeno', 'control-humedad', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos'],
    image: '/images/products/page06-8.webp',
  },
  // === Uniforme Deportivo ===
  {
    id: 'montesimone-r-antibacterial',
    name: 'Montesimone R Antibacterial',
    base: '33590',
    composition: '100% poliéster reciclado',
    weave: 'Punto',
    weight: '132 +-12 g/m2',
    width: '148 +- 3 cm',
    technologies: ['control-humedad', 'libertad-de-movimiento', 'antibacterial', 'proteccion-solar', 'sostenible'],
    printRoutes: ['Unicolor', 'Davos'],
    image: '/images/products/page07-11.webp',
  },
  {
    id: 'montesimone',
    name: 'Montesimone',
    base: '33003',
    composition: '100% poliéster',
    weave: 'Punto',
    weight: '132 +-12 g/m2',
    width: '151 +- 3 cm',
    technologies: ['control-humedad', 'libertad-de-movimiento', 'antibacterial', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page07-11.webp',
  },
  {
    id: 'hydrotech',
    name: 'Hydrotech',
    base: '33455',
    composition: '100% poliéster',
    weave: 'Punto',
    weight: '138 +-8 g/m2',
    width: '151 +- 3 cm',
    technologies: ['desempeno', 'control-humedad', 'proteccion-solar', 'libertad-de-movimiento'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page07-11.webp',
  },
  {
    id: 'hydrotech-antibacterial',
    name: 'Hydrotech Antibacterial',
    base: '33472',
    composition: '100% poliéster',
    weave: 'Punto',
    weight: '138 +-8 g/m2',
    width: '151 +- 3 cm',
    technologies: ['control-humedad', 'libertad-de-movimiento', 'antibacterial', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page07-11.webp',
  },
  // === Uniforme Diario - Faldas - Blazers ===
  {
    id: 'stefano-r',
    name: 'Stefano R',
    base: '23195',
    composition: '65% poliéster reciclado, 35% viscosa',
    weave: 'Plano',
    weight: '185 +-10 g/m2',
    width: '151 +- 3 cm',
    technologies: ['desempeno', 'proteccion-solar', 'sostenible'],
    printRoutes: ['Unicolor'],
    image: '/images/products/page08-14.webp',
  },
  {
    id: 'dynamic',
    name: 'Dynamic',
    base: '22587',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '161 +-8 g/m2',
    width: '151 +- 2 cm',
    technologies: ['control-humedad', 'desempeno', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page08-14.webp',
  },
  {
    id: 'microdrill',
    name: 'Microdrill',
    base: '22215',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '157 +-8 g/m2',
    width: '150 +- 2 cm',
    technologies: ['desempeno', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page08-14.webp',
  },
  {
    id: 'alviero-stretch',
    name: 'Alviero Stretch',
    base: '22528',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '210 +-10 g/m2',
    width: '152 +- 3 cm',
    technologies: ['libertad-de-movimiento', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page08-14.webp',
  },
  {
    id: 'novastretch-lc',
    name: 'Novastretch LC',
    base: '23156',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '260 +-13 g/m2',
    width: '153 +- 3 cm',
    technologies: ['antimanchas', 'control-humedad', 'proteccion-solar', 'libertad-de-movimiento'],
    printRoutes: ['Unicolor', 'Rotativa', 'Sublimación'],
    image: '/images/products/page08-14.webp',
  },
  {
    id: 'universal-ripstop',
    name: 'Universal Ripstop',
    base: '22240',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '132 +-6 g/m2',
    width: '151 +- 2 cm',
    technologies: ['antifluido-repelencia', 'durabilidad', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page08-14.webp',
  },
  // === Buzos - Hoodies - Perchados ===
  {
    id: 'celta',
    name: 'Celta',
    base: '33615',
    composition: '100% poliéster',
    weave: 'Punto',
    weight: '224 +-12 g/m2',
    width: '163 +- 3 cm',
    technologies: ['libertad-de-movimiento', 'proteccion-solar', 'termico'],
    printRoutes: ['Unicolor', 'Davos', 'Sublimación'],
    image: '/images/products/page09-20.webp',
    isNew: true,
  },
  {
    id: 'dual',
    name: 'Dual',
    base: '44665',
    composition: '100% poliéster',
    weave: 'Punto',
    weight: '197 +-7 g/m2',
    width: '157 +- 3 cm',
    technologies: ['control-humedad', 'libertad-de-movimiento', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos'],
    image: '/images/products/page09-20.webp',
  },
  {
    id: 'microtitan-plus',
    name: 'Microtitan Plus',
    base: '33492',
    composition: '100% poliéster',
    weave: 'Punto',
    weight: '173 +-13 g/m2',
    width: '149 +- 3 cm',
    technologies: ['proteccion-solar', 'termico'],
    printRoutes: ['Unicolor'],
    image: '/images/products/page09-20.webp',
  },
  // === Blusas - Camisas ===
  {
    id: 'metro-lc',
    name: 'Metro LC',
    base: '22396',
    composition: '100% poliéster',
    weave: 'Plano',
    weight: '109 +- 5 g/m2',
    width: '151 +- 3 cm',
    technologies: ['control-humedad', 'antimanchas', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page11-27.webp',
  },
  {
    id: 'queen',
    name: 'Queen',
    base: '22693',
    composition: '85% poliéster, 15% algodón',
    weave: 'Plano',
    weight: '100 +-5 g/m2',
    width: '170 +- 3 cm',
    technologies: ['algodon', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page11-27.webp',
  },
  {
    id: 'andes-r',
    name: 'Andes R',
    base: '23192',
    composition: '100% poliéster reciclado',
    weave: 'Plano',
    weight: '113 +- 5 g/m2',
    width: '150 +- 3 cm',
    technologies: ['control-humedad', 'antimanchas', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page11-27.webp',
  },
  {
    id: 'alessio',
    name: 'Alessio',
    base: '22293',
    composition: '85% poliéster, 15% algodón',
    weave: 'Plano',
    weight: '112 +-8 g/m2',
    width: '153 +- 3 cm',
    technologies: ['algodon', 'proteccion-solar'],
    printRoutes: ['Unicolor', 'Rotativa', 'Davos', 'Sublimación'],
    image: '/images/products/page11-27.webp',
  },
] as const satisfies readonly Fabric[];
