import type { Technology } from './types';

export const TECHNOLOGIES = [
  {
    id: 'proteccion-solar',
    name: 'Protección Solar',
    icon: '/images/tech/proteccion-solar.png',
    description: 'Protección contra rayos UV',
    expandedDescription: 'Protección contra rayos UV',
  },
  {
    id: 'impermeabilidad',
    name: 'Impermeable',
    icon: '/images/tech/impermeabilidad.png',
    description: 'Resistencia al agua',
    expandedDescription: 'Resistencia al agua',
  },
  {
    id: 'durabilidad',
    name: 'Antirrasgado',
    icon: '/images/tech/durabilidad.png',
    description: 'Resistencia al desgaste y rasgado',
    expandedDescription: 'Resistencia al desgaste y rasgado',
  },
  {
    id: 'antifluido-repelencia',
    name: 'Antifluido',
    icon: '/images/tech/antifluido.png',
    description: 'Repelencia de fluidos',
    expandedDescription: 'Repelencia de fluidos',
  },
  {
    id: 'libertad-de-movimiento',
    name: 'Elasticidad Stretch',
    icon: '/images/tech/elasticidad-stretch.png',
    description: 'Elasticidad y comodidad de movimiento',
    expandedDescription: 'Elasticidad y comodidad de movimiento',
  },
{
    id: 'desempeno',
    name: 'Desempeño',
    icon: '/images/tech/desempeno.png',
    description: 'Alto rendimiento textil',
    expandedDescription: 'Alto rendimiento textil',
  },
  {
    id: 'control-humedad',
    name: 'Secado Rápido',
    icon: '/images/tech/secado-rapido.png',
    description: 'Gestión de humedad y secado rápido',
    expandedDescription: 'Gestión de humedad y secado rápido',
  },
  {
    id: 'antibacterial',
    name: 'Antibacterial',
    icon: '/images/tech/antibacterial.png',
    description: 'Protección antibacteriana',
    expandedDescription: 'Protección antibacteriana',
  },
  {
    id: 'antimanchas',
    name: 'Antimanchas',
    icon: 'ShieldCheck',
    description: 'Resistencia a manchas',
    expandedDescription: 'Resistencia a manchas',
  },
  {
    id: 'clororresistente',
    name: 'Clororresistente',
    icon: '/images/tech/clororresistente.png',
    description: 'Resistencia al cloro',
    expandedDescription: 'Resistencia al cloro',
  },
  {
    id: 'termico',
    name: 'Térmico',
    icon: '/images/tech/termico.png',
    description: 'Regulación térmica',
    expandedDescription: 'Regulación térmica',
  },
  {
    id: 'solidez-a-la-luz',
    name: 'Solidez a la Luz',
    icon: 'Sun',
    description: 'Resistencia a la decoloración por luz',
    expandedDescription: 'Resistencia a la decoloración por luz',
  },
  {
    id: 'sostenible',
    name: 'Sostenible — Hilos Reciclados',
    icon: '/images/tech/sostenible-hilos-reciclados.png',
    description: 'Elaborado con hilos reciclados',
    expandedDescription: 'Elaborado con hilos reciclados',
  },
] as const satisfies readonly Technology[];
